apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hazelcast-rolebinding
  namespace: demo-hazelcast
subjects:
  - kind: ServiceAccount
    name: default
    namespace: demo-hazelcast
roleRef:
  kind: Role
  name: hazelcast-role
  apiGroup: rbac.authorization.k8s.io
