spring:
  datasource:
    url: jdbc:postgresql://postgresql.demo-hazelcast.svc.cluster.local:5432/demo
    username: demo_user
    password: demo_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Logging Configuration
logging:
  level:
    org:
      hibernate: DEBUG
